sudo: required

services:
  - docker

env:
  - TARGET=communication-support
  - TARGET=extensibility
  - TARGET=fault-resilience
  - TARGET=horizontal-scalability
  - TARGET=replaceability

install:
  - cd $TARGET
  - ./install.sh

script:
  - ./script.sh
