version: "2"
services:
  frontend1:
    build:
      context: .
      dockerfile: Dockerfile-frontend1
    image: diunipisocc/extensibility:frontend1
    links:
    - backend
    ports:
    - 3001:3001
    environment:
      NODE_CONFIG: '{"frontend1": {
                        "port": 3001,
                        "backend_endpoint": "http://backend:3000"
                    }}'

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: diunipisocc/extensibility:backend
