version: "2"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: diunipisocc/communication-support:frontend
    links:
    - backend
    ports:
    - 3001:3001
    environment:
      NODE_CONFIG: '{"frontend": {
                        "port": 3001,
                        "backend_endpoint": "http://backend:3000"
                    }}'

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: diunipisocc/communication-support:backend
