version: "2"
services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    image: diunipisocc/horizontal-scalability:consumer
    links:
    - producer
    environment:
      NODE_CONFIG: '{"consumer": {
                        "producer_endpoint": "http://producer:3000"
                    }}'

  producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    image: diunipisocc/horizontal-scalability:producer
    ports:
    - 3000:3000
